### ISSUE TITLE
chgrp error through installation

### ISSUE THREAD

**Issue by Kharestani** [jarves/jarves-standard#1]
Hi 
Thanks for your effort
I install the package with composer and then I ran `php bin/console propel:model:build` but there is an error `Operation to chgrp the file C:\wamp\www\MyjarveStandardProject\var\cache\
dev/core_gettext_plural_fn_en.php to staff is
  denied.`
I am using WAMP and PHP 5.6.20

Thanks

**Comment by marcj** [comment]
You need to adjust `app/config/config.jarves.xml`, `groupOwner` to a group you running wamp. You can also disable the whole behavior by changing `disableModeChange="false" to true.

**Comment by Kharestani** [comment]
Thank you for your fast response
