### ISSUE TITLE
No staff group on my dev http

### ISSUE THREAD

**Issue by tachyon-ops** [jarves/jarves-standard#3]
Hi there... so... staff from mac world?

`Operation to chgrp the file /var/www/html/projects/jarves-standard/var/cache/dev/core_gettext_plural_fn_en.php to staff is denied.`

**Comment by marcj** [comment]
Try to change the group to "_www" or disable it completely with disableModeChange. https://github.com/jarves/jarves-standard/blob/master/app/config/config.jarves.xml#L75

**Comment by tachyon-ops** [comment]
Inserted my group for file permissions and it worker. Checking other errors, but this is closed. Thanks
