### ISSUE TITLE
Propel - unable to connect

### ISSUE THREAD

**Issue by tachyon-ops** [jarves/jarves-standard#4]
Hi there,

I've setup a mysql db, populated conf.jarves.xml with the proper data... and still gave me this:

```
$ php bin/console propel:database:create
  [Propel] Exception caught      
  Unable to open connection    
```

How can I debug it? I'm a bit on the dark with symfony and propel...
Thanks in advance

**Comment by marcj** [comment]
I removed that command because it doesn't work always. Just create the database by hand in your tool of favour.

**Comment by tachyon-ops** [comment]
Could you update the readme here then? I am not sure what to do next, suppose this should give me a working installation... 

just want test it and then I dive into the details.

**Comment by tachyon-ops** [comment]
You're fast :+1:
