### ISSUE TITLE
vhost

### ISSUE THREAD

**Issue by tachyon-ops** [jarves/jarves-standard#5]
Hi there,

Got it up and running now with your directions. I'm already enjoying it :) great work!
Now... one last desire: vhost.

Checked http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html but... not that straightforward... I'm almost inclined to write an index.php and check how the server gets initialized on bin/console server:run

Do you have any tip on it?
also, if you had a chat place would be better as this is no bug

**Comment by marcj** [comment]
So what do you actually want to do?

**Comment by tachyon-ops** [comment]
I have vhosts on ~/web/example.com/public_html, from vestacp... so would be great to maintain it's pattern and leave all code on ~/web/example.com/private while the app.php would be on ~/web/example.com/public_html
Or... on a production system with multiple virtual hosts, I would have to make the jarves site exist on a different port and proxy it on a vhost. Possible as well... perhaps the simpler solution
Can we assign a port on `php bin/console server:run` ?

**Comment by tachyon-ops** [comment]
Or... if I use it as a rest, I could access it on a different port on the machine and have an angular js site on the public_html from a specific vhost

**Comment by marcj** [comment]
You should actually not move folders. The structure with `./web/` is important because Jarves places there frontend caches (compiled scss files for example) or the whole file manager handles all files in there.
Just let the current folder structure as is and point your webserver to `./web/` with a default index of `app.php`. Everything else will be a mess.

**Comment by tachyon-ops** [comment]
I see... then I should be able to access jarves on the jarves-standard/web/ folder on my webserver right? Because I am not able to.

`Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/html/projects/jarves-standard/var/cache/prod) ' in /var/www/html/projects/jarves-standard/var/bootstrap.php.cache:2523 Stack trace: #0 /var/www/html/projects/jarves-standard/var/bootstrap.php.cache(2484): Symfony\Component\HttpKernel\Kernel->buildContainer() #1 /var/www/html/projects/jarves-standard/var/bootstrap.php.cache(2273): Symfony\Component\HttpKernel\Kernel->initializeContainer() #2 /var/www/html/projects/jarves-standard/var/bootstrap.php.cache(2304): Symfony\Component\HttpKernel\Kernel->boot() #3 /var/www/html/projects/jarves-standard/web/app.php(32): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #4 {main} thrown in /var/www/html/projects/jarves-standard/var/bootstrap.php.cache on line 2523`

**Comment by tachyon-ops** [comment]
K... i'm working on it (permissions)

**Comment by marcj** [comment]
That is rather a permission issue. The webserver/php needs to write on `./var/`

**Comment by tachyon-ops** [comment]
Yes, all good. Many thanks @marcj !
