### ISSUE TITLE
non-existent service "jarves.cache.backend.apc"

### ISSUE THREAD

**Issue by tachyon-ops** [jarves/jarves-standard#6]
Hi, i'm testing on another server...

``````
$ composer install
You have requested a non-existent service "jarves.cache.backend.apc". ```

Have you ever seen this error?
``````

**Comment by tachyon-ops** [comment]
updated everything and re-installing...

**Comment by marcj** [comment]
Yeah, you need to update to newest version. This is already fixed in dev-master

**Comment by tachyon-ops** [comment]
can't find that branch...

**Comment by marcj** [comment]
Just fire `composer update jarves/jarves`

**Comment by tachyon-ops** [comment]
It worked, but jarves login is not formated... suppose it's another issue. this one got resolved with composer update jarves/jarves

Once again: thanks!

**Comment by marcj** [comment]
Guess you have no sass installed on your new server. Note: when you install sass later you need to clear the `web/cache/` folder.

**Comment by tachyon-ops** [comment]
Yes, you're right. Now, how can I re-build sass? composer install didn't worked...

**Comment by marcj** [comment]
Remove all caches in web/cache. `rm -rf web/cache/*`

**Comment by tachyon-ops** [comment]
It should be generated as I access it? It's not working for me... is there a cmd to regenerate cache (sass)?

**Comment by marcj** [comment]
Its automatically generated when there's no cache, correct. If it doesn't work:
1. Are there any files in `web/cache/scss/bundles/` ?
2. Do you get any error message?
3. Can you make sure you can open `sass` in  the console?

**Comment by tachyon-ops** [comment]
executing sass on the console outputed a warning notice to upgrade from my old 1.9 ruby instalation. upgraded to ruby 2.2 and re-removed as you specified.

1 - server1 bundles]$ ls outputs only jarves
2 - no error message
3 -  sass -v outputs Sass 3.4.22 (Selective Steve)

**Comment by marcj** [comment]
What's in cache/scss/bundles/jarves/admin/css/jarves/ and in cache/scss/bundles/jarves/admin/css/jarves/Checkbox.css ?

**Comment by tachyon-ops** [comment]
1 - cache/scss/bundles/jarves/admin/css/jarves/ outputs a bunch of css files (Button.css ButtonGroup.css ... )
2 - cache/scss/bundles/jarves/admin/css/jarves/Checkbox.css exists

Indeed I have no clue...

**Comment by marcj** [comment]
What's in there?

**Comment by tachyon-ops** [comment]
1-

@server1 jarves-standard]$ ls -lah web/cache/scss/bundles/jarves/admin/css/jarves/
total 100K
drwxrwxr-x 3 admin admin 4.0K May 11 20:20 .
drwxrwxr-x 3 admin admin 4.0K May 11 20:20 ..
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Button.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 ButtonGroup.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Checkbox.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Content.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Dashboard.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Dialog.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Editor.css
drwxrwxr-x 2 admin admin 4.0K May 11 20:20 Field
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Field.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Files.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Helpsystem.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Input.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 List.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Login.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 MainMenu.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 ObjectTree.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Search.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Select.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Slider.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 TabGroup.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Table.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 Window.css
-rw-rw-r-- 1 admin admin   29 May 11 20:20 WindowList.css

2 - @server1 jarves-standard]$ cat web/cache/scss/bundles/jarves/admin/css/jarves/Checkbox.css
/\* compiled at 1462986632 */

Ring any bell?

**Comment by marcj** [comment]
Yeah seems sass is not reachable by php. You could try to fire this script:

``` php
<?php

system('sass -v', $exitCode);
var_dump($exitCode);
```

**Comment by tachyon-ops** [comment]
I see... 

Output: public_html/jarves-standard/test.php:4:int 127

What's supposed to output? From 'php test.php' it outputs

```
jarves-standard]$ php test.php 
Sass 3.4.22 (Selective Steve)
/home/$user/web/$domain/public_html/jarves-standard/test.php:4:
int(0)
```

Hum... never thought about using sass on php

**Comment by tachyon-ops** [comment]
What sass compiler in php do you use?

Edit\* Nevermind. From httpd log: 

```
sh: sass: command not found
sh: sass: command not found
zend_mm_heap corrupted
(...)
[Thu May 12 14:13:24 2016] [notice] child pid 32517 exit signal Segmentation fault (11)
[Thu May 12 14:13:48 2016] [notice] child pid 4711 exit signal Segmentation fault (11)
```

I'm trying to figure it out... seams at first I hadn't installed, now it seams I have but exits with a Seg fault. Checking...

Edit *\* 

```
$ sh sass -v
/usr/local/rvm/gems/ruby-2.2.4/bin/sass: line 9: require: command not found
/usr/local/rvm/gems/ruby-2.2.4/bin/sass: line 11: version: command not found
/usr/local/rvm/gems/ruby-2.2.4/bin/sass: sass: line 15: syntax error near unexpected token `('
/usr/local/rvm/gems/ruby-2.2.4/bin/sass: sass: line 15: `  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding'
```

**Comment by tachyon-ops** [comment]
I don't get it...

sh sass -v also doesn't work on my dev server where jarves works good.
must be something else... follow symlinks is set up on httpd...
don't know. where on the code is the sass cache compiled?

**Comment by marcj** [comment]
Nowhere, it is using $PATH. You can see it here: https://github.com/jarves/jarves/blob/master/AssetHandler/ScssHandler.php#L71

**Comment by tachyon-ops** [comment]
Can I compile somehow manually?

**Comment by marcj** [comment]
No, because the system does not know where everywhere are resources used. You need to manually clear the `web/cache/*` folder.

**Comment by tachyon-ops** [comment]
Well, I'll just do a couple more re-installs on centos 6.7, and on vestacp...

Thanks for everything mate

**Comment by tachyon-ops** [comment]
Yes, tested centos 7 and it is also giving me bad css...

```
$ sass -v
Sass 3.4.22 (Selective Steve)
[admin@localhost jarves-standard]$ npm -v
2.15.1
[admin@localhost jarves-standard]$ node -v
v0.12.14
[admin@localhost jarves-standard]$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
[admin@localhost jarves-standard]$ php -v
PHP 5.6.21 (cli) (built: Apr 28 2016 07:07:46) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

also not working good with standard "php bin/console server:run"
Have you tried to install in a fresh vm? What OSs have you tested?

**Comment by marcj** [comment]
> also not working good with standard "php bin/console server:run"

What does "not working good" mean?

I actually only tried on OSX and ubuntu. I'm going to try it later in centos :)

**Comment by tachyon-ops** [comment]
I mean this: https://snag.gy/5q29eX.jpg
css is not being built as we've seen before. perhaps it would be wise to make also commands available to rebuild on the cmd line...

Cool! Keep me posted as you get news from centos :)

**Comment by marcj** [comment]
> perhaps it would be wise to make also commands available to rebuild on the cmd line...

That's not possible for all use cases.

However I'll look into it later

**Comment by tachyon-ops** [comment]
Any news? :) I would love to dev over it for my production server

**Comment by marcj** [comment]
We pushed lately some fixes for this behavior. You should get now a detailed error message when sass is not able to parse scss files.

**Comment by tachyon-ops** [comment]
Ok, the cache thing is not present any more on `composer install`.
Now we know why:

```
{
    "status": 500,
    "error": "RuntimeException",
    "message": "sass binary not found. Please install sass first and make its in $PATH. Command not found",
    "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/jarves\/jarves\/AssetHandler\/ScssHandler.php",
    "line": 88,
    "trace": [
        {
            "function": "compileFile",
            "class": "Jarves\\AssetHandler\\ScssHandler",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/jarves\/jarves\/PageResponse.php",
            "line": 358,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "handleAsset",
            "class": "Jarves\\PageResponse",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/jarves\/jarves\/PageResponse.php",
            "line": 415,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "addAsset",
            "class": "Jarves\\PageResponse",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/jarves\/jarves\/Admin\/AdminAssets.php",
            "line": 135,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "addMainResources",
            "class": "Jarves\\Admin\\AdminAssets",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/jarves\/jarves\/Controller\/AdminLoginController.php",
            "line": 41,
            "type": "->",
            "args": []
        },
        {
            "function": "showLoginAction",
            "class": "Jarves\\Controller\\AdminLoginController",
            "file": null,
            "line": null,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "call_user_func_array",
            "class": null,
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php",
            "line": 139,
            "type": null,
            "args": [
                "array",
                "array"
            ]
        },
        {
            "function": "handleRaw",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/HttpKernel.php",
            "line": 62,
            "type": "->",
            "args": [
                "object",
                "integer"
            ]
        },
        {
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/HttpKernel\/Kernel.php",
            "line": 169,
            "type": "->",
            "args": [
                "object",
                "integer",
                "boolean"
            ]
        },
        {
            "function": "handle",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/web\/app_dev.php",
            "line": 30,
            "type": "->",
            "args": [
                "object"
            ]
        },
        {
            "function": "require",
            "class": null,
            "file": "\/home\/admin\/web\/localhost\/public_html\/projects\/jarves-standard\/vendor\/symfony\/symfony\/src\/Symfony\/Bundle\/FrameworkBundle\/Resources\/config\/router_dev.php",
            "line": 40,
            "type": null,
            "args": [
                "string"
            ]
        }
    ]
}
```

I'm going to investigate it for a while. Will post if anything comes up. Thanks @marcj

**Comment by marcj** [comment]
Well yepp, seems you need to make sass available in your global $PATH. (or create a symlink from /usr/bin/sass to your sass)

**Comment by tachyon-ops** [comment]
Right. I'm using user based installations... will try a symlink

**Comment by tachyon-ops** [comment]
Environment path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Sass on system('sass -v', var):
int(127)

Which sass system('which sass', var):
/usr/local/bin/sass 

User specific situation. Must be some php config lock.
