### ISSUE TITLE
Installation fails to Propel\Runtime\Connection\Exception\ConnectionException

### ISSUE THREAD

**Issue by rabidus** [jarves/jarves-standard#7]
When trying to install jarves-standard, I get following error after configuring app/config/config.jarves.xml file (database settings and groupOwner).

Database also exists, and I'm able to connect into it with given credentials in settings.

Error goes:

> me@master:~/dev/jarves-standard$ php bin/console propel:migration:diff
> 
>  [Propel\Runtime\Connection\Exception\ConnectionException]  
>  Unable to open connection                                  
> 
>  [Propel\Runtime\Adapter\Exception\AdapterException]  
>  Unable to open PDO connection                        
> 
>  [PDOException]  
>  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)                                                                                            

`php bin/console propel:model:build` however runs without problems

What am I doing wrong, or is this a bug?

**Comment by marcj** [comment]
Please try to reset the cache using `php app/console cache:clear`.

**Comment by rabidus** [comment]
Right, that was it. Thank you!
