### ISSUE TITLE
Unrecognized options "admin, router" under "jarves"

### ISSUE THREAD

**Issue by grrinch** [jarves/jarves-standard#9]
Hi,
following the installation instructions and I'm getting the following errors:
```

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

                                                                                 
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized options "admin, router" under "jarves"                            
                                                                                 

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                                     
  [RuntimeException]                                                                 
  An error occurred when executing the "'cache:clear --no-warmup'" command:          
                                                                                     
    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
    Unrecognized options "admin, router" under "jarves"
```

Tried installing it "the hard way", but there are some other errors I have to still try figure out. 

I'm hoping raising an issue with the above might help me as well as the other users.

**Comment by marcj** [comment]
We added in the last days new configuration options to disable/enable administration and frontend router. To get stuff working, just add

``` yml
jarves:
    admin: true
    router: true
```

in your app/config/config.yml.

**Comment by marcj** [comment]
Ah I see, its vice versa. Just call `composer update jarves/jarves` to get new jarves version

**Comment by grrinch** [comment]
Hi,

thanks for a quick reply. 
I couldn't composer update jarvis/jarvis showing some issues with propel not being configured, however I managed to workaround it by deleting 

``` yaml
jarves:
    admin: true
    router: true
```

from app/config/config.yml, like you said. 

Issue ok to be closed :) :+1:
